### ISSUE TITLE
Where is the installer?

### ISSUE THREAD

**Issue by chjan** [flipswitchingmonkey/FlexASIO_GUI#12]
Trying to install this GUI, but in the install folder, there is no installer? 

Alternatively, where do I put the folder if it can be done manually?

Thanks!

**Comment by dechamps** [comment]
Were you looking for the [releases page](https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases)?

**Comment by chjan** [comment]
Solved. Thanks. However, could not say that about Flexasio. No sound input achieved. 

 

Kind regards

Carl Henrik

**Comment by dechamps** [comment]
If you're having an issue with FlexASIO you might want to [open an issue against FlexASIO](https://github.com/dechamps/FlexASIO/issues), not FlexASIO GUI.

**Comment by chjan** [comment]
indeed.
