### ISSUE TITLE
using flexasio v1.5 cant run flexasio_gui.exe

### ISSUE THREAD

**Issue by fingerx** [flipswitchingmonkey/FlexASIO_GUI#15]
hi,my win10 version is v1909.18363.1441. download last flexasio_gui and last flexasio  cant open gui exe, no error log.  need your help,thanks

**Comment by flipswitchingmonkey** [comment]
Sorry, I'm not actually working on this right now (as I'm spending 99% of my time on a Mac currently). I hope to get around to looking at it eventually

**Comment by flipswitchingmonkey** [comment]
I just published version 0.3, can you please try again?

**Comment by fingerx** [comment]
@flipswitchingmonkey  thanks

**Comment by fingerx** [comment]
@uisng v1.5 and v1.7 cant open gui exe, no error log.

**Comment by flipswitchingmonkey** [comment]
can you send your .toml file please?
