### ISSUE TITLE
Installer doesnt work Windows 7 Professional x86

### ISSUE THREAD

**Issue by JugoLoco** [flipswitchingmonkey/FlexASIO_GUI#18]
Installer version may not compatible whit Win 7 pro x86 and FlexiASIO 1.7a x86

**Comment by Leepshin** [comment]
It's not compatible because all the files are for "LINUX" and not Windows.

**Comment by flipswitchingmonkey** [comment]
uhm what? what files are for 'Linux'?

It may be that some libraries are not supported on win 7 any more. Win 7  has been EOL for over a year now.

**Comment by Leepshin** [comment]
Is there an update then so it can be opened in Windows 11?

Cheers
Lee

**Comment by flipswitchingmonkey** [comment]
I don't have Win 11 yet. What happens?

**Comment by Leepshin** [comment]
Sorry Mike I'm gettin a wee bit ahead of myself there.

I just figured as a developer you'd already have access. I'm still on
Windows 10 but you know what Microsoft operating systems are like. All it
takes is one tech fart and your existing system becomes obsolete.  LOL

If you've got an update or a specific installation tool to open the files
I'd greatly appreciate if you could let me know as I'm on the lookout for
every kind of ASIO driver there is. Latency is my nemesis and I'm
determined to obliterate it.

Kind regards


Lee
