### ISSUE TITLE
How to install or use on windows

### ISSUE THREAD

**Issue by johnenosh92** [flipswitchingmonkey/FlexASIO_GUI#2]
Please suggest how to install or use this GUI on my windows PC that has FlexASIO installed.

**Comment by flipswitchingmonkey** [comment]
Just download the release installer and run it. It should find the flexasio config file as long as it is at the default location.

**Comment by sheathompson** [comment]
I'm having trouble with this as well, maybe I'm missing something but there is no installer recognized by windows 10 - all the files included ask me to search for a compatible program to open it

HALP! I would love to use your GUI

**Comment by flipswitchingmonkey** [comment]
On the right hand side, under Releases.

https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/download/v0.3/FlexASIO.GUIInstaller_0.3.exe

![grafik](https://user-images.githubusercontent.com/6930367/120386028-64ab7b00-c328-11eb-8ebc-8e6cc7b7b0b2.png)

**Comment by andrewgray1965** [comment]
that wasn't obvious to me either ...
