### ISSUE TITLE
.NET core 3.1.0 not found error, despite installing it

### ISSUE THREAD

**Issue by nutel65** [flipswitchingmonkey/FlexASIO_GUI#23]
I got an error message:
![image](https://user-images.githubusercontent.com/44318430/139708206-3f312475-9b18-4dd8-8fff-1a956667c662.png)
The problem still occurs after installing the .NET core from [the link that popped up after clicking "yes"](https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.1.0&arch=x64&rid=win10-x64&gui=true&apphost_version=3.1.20).

What I tried to do:
- rebooting
- Installing actual 3.1.0 version from [here](https://versionsof.net/core/3.1/3.1.0/) (because what I got from the first link was v.3.1.2.0)
- rebooting again

**Comment by flipswitchingmonkey** [comment]
I just compiled it with .net 5.0, maybe give that one a try? https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/tag/v0.31-net5.0

**Comment by nutel65** [comment]
![image](https://user-images.githubusercontent.com/44318430/139834815-1d500667-1275-4b47-8ec2-a2045bd4bbc9.png)
I figured out that I installed wrong version: `.NET Core Runtime` instead of `.NET Core Desktop Runtime`. The message is kind of misleading as the error says you need `.NET Core`, and not `.NET Core Desktop`

That said, you could amend back bb8c990c3852d83d3e068bd51f3f1adc753166ad
