### ISSUE TITLE
FlexASIOGui request for Microsoft.WindowsDesktop.app even if i have it installed

### ISSUE THREAD

**Issue by alfonso73** [flipswitchingmonkey/FlexASIO_GUI#24]
Hi, FlexASIOGui request for Microsoft.WindowsDesktop.app even if i have it installed.
![Screenshot 2021-11-05 173239](https://user-images.githubusercontent.com/3230434/140546114-4ea3b1dc-c86c-422a-9e65-062668c5431d.png)

**Comment by e33et** [comment]
I've got the same issue even when got net 5.0 installed!

**Comment by e33et** [comment]
I've got this fixed by installed from the middle links on the .net site, srry for my l8t response of my workaround!

**Comment by e33et** [comment]
> Hi, FlexASIOGui request for Microsoft.WindowsDesktop.app even if i have it installed. ![Screenshot 2021-11-05 173239](https://user-images.githubusercontent.com/3230434/140546114-4ea3b1dc-c86c-422a-9e65-062668c5431d.png)

I've got this fixed by installed from the middle link on the .net site, srry for my l8t response of my workaround!

This windowsdesktop-runtime-5.0.13-win-x64.exe, I believe it was!
