### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by HerrLanginger** [flipswitchingmonkey/FlexASIO_GUI#28]
I'm sure, that this question completely stupid - but I'm too
how do i install this thing?

**Comment by flipswitchingmonkey** [comment]
![image](https://user-images.githubusercontent.com/6930367/149833980-76bb5c39-d7cd-471f-ae2b-908d511fb567.png)

**Comment by flipswitchingmonkey** [comment]
for net6.0 https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/tag/v0.33
