### ISSUE TITLE
.NET 5.0 is reaching end of life

### ISSUE THREAD

**Issue by ChrisTorng** [flipswitchingmonkey/FlexASIO_GUI#29]
According to [Versions of .NET](https://versionsof.net/core/), .NET 5.0 is reaching end of life by 2020/5/10. This project should be upgrade to .NET 6.0.

**Comment by ChrisTorng** [comment]
I found [Building a net5.0 targeted app which can run on net6.0 runtime](https://stackoverflow.com/questions/71272243/building-a-net5-0-targeted-app-which-can-run-on-net6-0-runtime) and [Running .NET Core Apps on a Framework other than Compiled Version?](https://weblog.west-wind.com/posts/2021/Jun/15/Running-NET-Core-Apps-on-a-Framework-other-than-Compiled-Version) may help. If you can't upgrade now, or consider to those who installed .NET 5.0 runtime before.

And I suggest to change the message of 'To run this application, you must install .NET.' to 'To run FlexASIO GUI, you must install .NET 5.0/6.0 Desktop Runtime.'. Add this message also on README.md. That reduces everyone's time to looking for the right version to download, and also the unnecessary issues here.

**Comment by flipswitchingmonkey** [comment]
Re-compiled to target net6.0

https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/tag/v0.33
