### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by lucasblanes** [flipswitchingmonkey/FlexASIO_GUI#3]
Sorry, I'm really new to all of this. I just bought my Behringer interface and installed FlexAsio in my computer. I didn't change any configurations and I'm feeling that the standard config is not quite there yet. Since I'm not familiar with coding the config, I was trying to use your GUI to go through it. But I don't know how to open/install it. Can you help me, please?

**Comment by flipswitchingmonkey** [comment]
Sure. 

1. Install FlexASIO with their installer (1.5 currently) https://github.com/dechamps/FlexASIO/releases/tag/flexasio-1.5
2. Download my installer (0.1 currently) https://github.com/flipswitchingmonkey/FlexASIO_GUI/releases/tag/0.1
3. Install it as well
4. You don't need to create the flexasio config file by hand (if you already did and are unsure if it is working, just rename it or delete it) 
5. Start FlexASUI GUI and select the backend (I suggest WASAPI), the input device and output device by clicking on the name of each, and the leave the rest as is for now.
6. Now click on "Save to Default FlexASIO.toml". This will create that config file for you.
7. That's it. You should now be able to select flexasio as your ASIO device in your DAW or whererver.

**Comment by lucasblanes** [comment]
Thank you! I managed to install and start it, it's working just fine. I still need to test it with Amplitube 4 and my audio interface, but I'll start working and won't be able to test it right now. But I'm really happy, thank you for your help!
