### ISSUE TITLE
Unicode devices name encoding issue

### ISSUE THREAD

**Issue by edisonlee55** [flipswitchingmonkey/FlexASIO_GUI#30]
Related to #7.

The GUI does not handle the device with Unicode name correctly.
It is resulting in a corrupted config file.

> The input device name should be `麥克風 (2- USB Audio Device)`.
> Output should be `喇叭 (2- USB Audio Device)`.
> These texts are Chinese characters.

![image](https://user-images.githubusercontent.com/5277788/168321731-04e91d36-e4f1-4ce7-971e-8d375d6c8839.png)

**Comment by flipswitchingmonkey** [comment]
Thanks for the info, very interesting!

**Comment by dechamps** [comment]
It's worth noting that in theory you shouldn't have to do this. This is still a bug in FlexASIO GUI. Most likely it has something to do with something somewhere in FlexASIO GUI using codepage-dependent ("ANSI") Windows APIs instead of Unicode (UTF-16) APIs.
