### ISSUE TITLE
List all loopback devices in input device section in the app

### ISSUE THREAD

**Issue by Titanic4** [flipswitchingmonkey/FlexASIO_GUI#31]
Since [FlexASIO 1.9](https://github.com/dechamps/FlexASIO/releases/tag/flexasio-1.9) was released, you can use loopback device as the input device. The idea here is to make the app list also all the loopback devices that are available in the system. To actually use it, you have to add `[Loopback]` after the device name while separating both words with a single space. 
For example: 
The desired loopback device is named `G430 (4- Logitech G430 Gaming Headset)`- the whole name would need to be as follows: 
`G430 (4- Logitech G430 Gaming Headset) [Loopback]`
The [input] section of the flexASIO.toml after setting **this** device as the input would look like this: 
```
[input]
device = "G430 (4- Logitech G430 Gaming Headset) [Loopback]"
wasapiExclusiveMode = false
wasapiAutoConvert = true
channels = 8
```
Have you thought about adding such feature?

**Comment by dechamps** [comment]
All that's needed here is for FlexASIO GUI to include the latest PortAudio DLL.

In the mean time you can work around this yourself by taking the FlexASIO DLL (`FlexASIO\x64\portaudio.dll`) and replace the FlexASIO GUI DLL (`FlexASIOGUI\portaudio_x64.dll`) with it. Then the loopback devices will appear in FlexASIO GUI under WASAPI.

**Comment by flipswitchingmonkey** [comment]
0.34 packages the new portaudio 19.7
