### ISSUE TITLE
Loading of multiple configurations

### ISSUE THREAD

**Issue by Abolohit** [flipswitchingmonkey/FlexASIO_GUI#32]
Currently there is support for loading only the default FlexASIO.toml configuration file. 

The GUI itself supports saving various custom configurations by using the Save As button. However, there is no option for loading those saved custom configurations, right?

User needs to make the custom configuration every time and save it to the default FlexASIO.toml file for the configuration to load?

Is this a limitation of FlexASIO itself or the GUI?

**Comment by dechamps** [comment]
That's correct, FlexASIO only loads its configuration from `%userprofile%\FlexASIO.toml`. There is no way to load it from any other file.

If you want to go back and forth between multiple config files, the correct way to do it is to replace the `FlexASIO.toml` file when you want to switch to a different configuration. You can automate that process in any way you like (AutoHotkey, etc.).

**Comment by flipswitchingmonkey** [comment]
in 0.34 you can load alternative toml files
