### ISSUE TITLE
Simply does not open.

### ISSUE THREAD

**Issue by squidud** [flipswitchingmonkey/FlexASIO_GUI#33]
Title says it all. FlexASIO is installed, I install this program and it works fine, shows up in the start menu etc, it just doesn't launch. Maybe I'm a total moron here (very likely) but I'm not sure what I could be doing wrong.

**Comment by flipswitchingmonkey** [comment]
Have you checked that you have installed the https://dotnet.microsoft.com/en-us/download/dotnet/6.0 desktop runtime?

**Comment by squidud** [comment]
> Have you checked that you have installed the https://dotnet.microsoft.com/en-us/download/dotnet/6.0 desktop runtime?

Yup so turns out I am a moron. That's what it was, I appreciate it lol.

**Comment by TerminatorSAW2k** [comment]
Das Problem besteht noch, startet nur beim erstmaligen Nutzen, ich hab den Fehler auch.  

Bei einer Neuinstallation des der FlexASIO_GUI ist der Fehler nicht da und das Tool startet auf PC 2 normal.
