### ISSUE TITLE
"You must install .NET Desktop Runtime" -- Already installed

### ISSUE THREAD

**Issue by bgsulz** [flipswitchingmonkey/FlexASIO_GUI#39]
Apologies in advance for what is probably a banal question. I have installed .NET Desktop Runtime 6.0.10 -- find evidence below.
Despite this, application will not start.

![FlexASIOGUI_c2pHal4Wbb](https://user-images.githubusercontent.com/38191432/216756822-e5ed8b2c-c6de-48d8-a33c-3d3cdeea3cbf.png)

Clicking "Yes" causes the application to close. As far as I can tell, no task appears in Task Manager related to the installation.

If there is any more information you need, please do not hesitate to let me know.

***

The result of `dotnet --info`:
![WindowsTerminal_AO8AQQqSd8](https://user-images.githubusercontent.com/38191432/216756831-b70032d8-16df-4983-a1b7-8cafffca0937.png)

The installation folder. (All files within 6.0.10 seem to be present.)
![explorer_0qpnbXYEP0](https://user-images.githubusercontent.com/38191432/216756890-10c1680c-2fe5-449b-86ea-ab62f60ce0c7.png)

Environment variables, [if relevant;](https://github.com/microsoft/PowerToys/issues/20266) neither appears to be set.
![WindowsTerminal_oQdwTYwgp2](https://user-images.githubusercontent.com/38191432/216756843-38b9b161-6baa-4783-9785-f3be1b67172e.png)

Correct registry keys:
![regedit_66hOe50Ekp](https://user-images.githubusercontent.com/38191432/216756859-59adc64f-80fa-44f1-840c-4a170a768d70.png)
![regedit_34RG58gAeA](https://user-images.githubusercontent.com/38191432/216756864-932d5f2c-593b-4c75-aa1b-5643669ccede.png)

**Comment by bgsulz** [comment]
I resolved the issue. It had nothing to do with the program itself -- my mistake. It was caused by corrupt registry keys. 

If you have this problem, consider using the Microsoft [Program Install and Uninstall Troubleshooter.](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d) Select the option that says you have trouble installing a program, and choose for the program "Not Listed."

**Comment by KarimKuropka** [comment]
![grafik](https://github.com/user-attachments/assets/0a56fb81-aafb-4697-aed5-313f4277615a)

I get this error message, though .NET Core Desktop 6.0.33 is installed. I checked my registry and couldn't find anything deviating from the above registry (except the version number). Using the Program Install and Uninstall Troubleshooter does nothing.
Can you help me?
