### ISSUE TITLE
Request to add license

### ISSUE THREAD

**Issue by dylanmenzies** [flipswitchingmonkey/FlexASIO_GUI#43]
I would like to add FlexASIO and FlexASIO_GUI as tools as part of an installation for distribution. The FlexASIO license allows this, but the situation is unclear for FlexASIO_GUI. I would be very grateful if you can add the license from FlexASIO here.

**Comment by flipswitchingmonkey** [comment]
done ✅

**Comment by dylanmenzies** [comment]
Cheers!
