### ISSUE TITLE
Non-ASCII device names are not handled correctly

### ISSUE THREAD

**Issue by dechamps** [flipswitchingmonkey/FlexASIO_GUI#7]
Related: dechamps/FlexASIO#73

FlexASIO uses UTF-8 for device names everywhere, on the output of PortAudioDevices and in the configuration file.

However, FlexASIO GUI appears to be using the wrong encoding, as shown below when using the device name "Headéset":

![image](https://user-images.githubusercontent.com/866859/92302541-1027ca80-ef65-11ea-82e8-f18e2b97478a.png)

It seems to be interpreting the device name in some kind of local 8-bit encoding (maybe CP 850 or ISO-8859-1) instead of UTF-8. FlexASIO GUI then ends up writing a configuration file with the wrong device name.

**Comment by flipswitchingmonkey** [comment]
This should be fixed with v0.2 now. (had to encode the incoming names from Portaudio to Windows-1252 and back to Unicode...

**Comment by dechamps** [comment]
Thanks. I'm a bit confused as to why you'd need to do any conversions. I certainly don't do any in FlexASIO - PortAudio natively exposes device names as UTF-8 in its API, and I just use them as-is. I'm baffled as to why you'd need to use Windows-1252 anywhere, and I suspect it might cause problems with non-western-European character sets.

**Comment by flipswitchingmonkey** [comment]
Portaudio, at least as implemented in PortaudioSharp, give me the mangled names. But once converted to 1252 and then back to UTF, they appear fine. I don't have any way to configure Portaudio through the abstraction layer of portaudiosharp (don't even remember where I found that....). But it works. So... let's not question it too much :)
